# Generated by Django 2.1.1 on 2018-11-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slugStock', models.SlugField(max_length=255, unique=True)),
                ('categoria', models.CharField(max_length=25)),
                ('porciones', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('price', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
