# Generated by Django 2.0.5 on 2018-12-04 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfiles',
            name='perfil',
            field=models.CharField(choices=[('MNG', 'Administrador'), ('MSR', 'Mesero'), ('CJA', 'Cajero')], default='MSR', max_length=3),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='password',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
