# Generated by Django 2.1.1 on 2018-11-23 21:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comun', '0002_sucursal_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipoPago', models.CharField(choices=[('CRE', 'CREDITO'), ('DEB', 'DEBITO'), ('EFE', 'EFECTIVO'), ('CHE', 'CHEQUE')], default='EFE', max_length=3)),
                ('stockInicial', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('user_uuid', models.CharField(max_length=36)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comun.Estados')),
            ],
        ),
    ]
