# Generated by Django 2.0.5 on 2018-11-30 03:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipoPago', models.CharField(choices=[('CHE', 'CHEQUE'), ('CRE', 'CREDITO'), ('EFE', 'EFECTIVO'), ('DEB', 'DEBITO')], default='EFE', max_length=3)),
                ('monto', models.IntegerField()),
                ('monto_propina', models.IntegerField()),
                ('identificador', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('user_uuid', models.CharField(max_length=36)),
                ('pedido_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido')),
            ],
        ),
    ]
