# Generated by Django 2.1.3 on 2018-12-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipoPago',
            field=models.CharField(choices=[('DEB', 'DEBITO'), ('CHE', 'CHEQUE'), ('CRE', 'CREDITO'), ('EFE', 'EFECTIVO')], default='EFE', max_length=3),
        ),
    ]
