# Generated by Django 2.0.5 on 2018-12-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipoPago',
            field=models.CharField(choices=[('EFE', 'EFECTIVO'), ('CRE', 'CREDITO'), ('CHE', 'CHEQUE'), ('DEB', 'DEBITO')], default='EFE', max_length=3),
        ),
    ]
