# Generated by Django 2.0.5 on 2018-12-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20181204_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipoPago',
            field=models.CharField(choices=[('CHE', 'CHEQUE'), ('CRE', 'CREDITO'), ('DEB', 'DEBITO'), ('EFE', 'EFECTIVO')], default='EFE', max_length=3),
        ),
    ]
