# Generated by Django 2.1.3 on 2018-12-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_auto_20181204_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipoPago',
            field=models.CharField(choices=[('EFE', 'EFECTIVO'), ('DEB', 'DEBITO'), ('CRE', 'CREDITO'), ('CHE', 'CHEQUE')], default='EFE', max_length=3),
        ),
    ]
