# Generated by Django 2.1.3 on 2018-12-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20181204_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipoPago',
            field=models.CharField(choices=[('CHE', 'CHEQUE'), ('DEB', 'DEBITO'), ('EFE', 'EFECTIVO'), ('CRE', 'CREDITO')], default='EFE', max_length=3),
        ),
    ]
