# Generated by Django 2.1.3 on 2018-12-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_auto_20181204_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipoPago',
            field=models.CharField(choices=[('DEB', 'DEBITO'), ('CHE', 'CHEQUE'), ('EFE', 'EFECTIVO'), ('CRE', 'CREDITO')], default='EFE', max_length=3),
        ),
    ]
