# Generated by Django 2.1.3 on 2018-12-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_auto_20181204_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipoPago',
            field=models.CharField(choices=[('CRE', 'CREDITO'), ('EFE', 'EFECTIVO'), ('DEB', 'DEBITO'), ('CHE', 'CHEQUE')], default='EFE', max_length=3),
        ),
    ]
