# Generated by Django 2.1.3 on 2018-12-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_auto_20181204_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipoPago',
            field=models.CharField(choices=[('EFE', 'EFECTIVO'), ('CHE', 'CHEQUE'), ('CRE', 'CREDITO'), ('DEB', 'DEBITO')], default='EFE', max_length=3),
        ),
    ]
