# Generated by Django 2.0.5 on 2018-11-10 20:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMenu',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombreCategoria', models.CharField(max_length=95)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('_deleted', models.DateTimeField(auto_now=True)),
                ('_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ofertas',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaTermino', models.DateTimeField()),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('_deleted', models.DateTimeField(auto_now=True)),
                ('_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductosMenu',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombreProducto', models.CharField(max_length=45)),
                ('slugProducto', models.SlugField(max_length=255, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('_deleted', models.DateTimeField(auto_now=True)),
                ('_status', models.IntegerField()),
                ('productosMenuStock_uuid', models.CharField(max_length=36)),
                ('restaurant_uuid', models.CharField(max_length=36)),
                ('user_uuid', models.CharField(max_length=36)),
                ('categoria_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.CategoriaMenu')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosMenuStock',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stock_uuid', models.CharField(max_length=36)),
                ('porciones', models.IntegerField()),
                ('productosMenu_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ProductosMenu')),
            ],
        ),
        migrations.AddField(
            model_name='ofertas',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ProductosMenu'),
        ),
    ]
