# Generated by Django 2.0.5 on 2018-11-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20181114_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosmenu',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos_menu'),
        ),
    ]
