# Generated by Django 2.0.5 on 2018-11-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_productosmenu_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosmenu',
            name='imagen',
            field=models.ImageField(blank=True, default='nodisponible.png', upload_to='productos_menu'),
        ),
    ]
