# Generated by Django 2.0.5 on 2018-11-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20181118_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosmenu',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
