# Generated by Django 2.0.5 on 2018-12-04 04:21

from django.db import migrations, models
import django.db.models.deletion
import pedidos.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comun', '0001_initial'),
        ('mesas', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('numero', models.IntegerField(default=pedidos.models.Pedido.ids, editable=False, unique=True, verbose_name='Code')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('estadoPedido', models.CharField(choices=[('INIT', 'Pendiente'), ('WAIT', 'Espera'), ('OK', 'Entregado'), ('CNCL', 'Cancelado'), ('FNLZ', 'Finalizado'), ('PGD', 'Pagado')], default='INIT', max_length=5)),
                ('user_uuid', models.CharField(max_length=36)),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesas.Mesas')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comun.Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.IntegerField()),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('estadoPedido', models.CharField(choices=[('INIT', 'Pendiente'), ('WAIT', 'Espera'), ('OK', 'Entregado'), ('CNCL', 'Cancelado'), ('FNLZ', 'Finalizado')], default='INIT', max_length=5)),
                ('user_uuid', models.CharField(max_length=36)),
                ('pedido_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido')),
                ('productoMenu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.ProductosMenu')),
            ],
        ),
    ]
