# Generated by Django 2.0.5 on 2018-11-26 03:47

from django.db import migrations, models
import django.db.models.deletion
import pedidos.models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='pedido_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.IntegerField(default=pedidos.models.Pedido.ids, editable=False, unique=True, verbose_name='Code'),
        ),
    ]
