# Generated by Django 2.1.1 on 2018-11-17 00:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaStock',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombreCategoria', models.CharField(max_length=95)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField()),
                ('user_uuid', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoStock',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('porcion', models.IntegerField()),
                ('unidadMedida', models.CharField(max_length=22)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fechaElaboracion', models.DateTimeField()),
                ('fechaExpiracion', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField()),
                ('user_uuid', models.CharField(max_length=36)),
                ('categoria_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.CategoriaStock')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stockInicial', models.IntegerField()),
                ('StockDescontado', models.IntegerField()),
                ('StockFinal', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField()),
                ('user_uuid', models.CharField(max_length=36)),
            ],
        ),
        migrations.AddField(
            model_name='productostock',
            name='stock_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock'),
        ),
    ]
