# Generated by Django 2.0.5 on 2018-11-25 01:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoStock',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('porcion', models.IntegerField()),
                ('unidad_medida', models.CharField(max_length=22)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('no_perecible', models.BooleanField(default=False)),
                ('categoria', models.CharField(choices=[('PES', 'Pescados y Mariscos'), ('CAR', 'Carnes rojas y blancas'), ('DES', 'Despensa'), ('FRU', 'Frutas'), ('OTR', 'Otros'), ('PAS', 'Pastaleria'), ('BEB', 'Bebidas y Licores'), ('PPD', 'Productos Preparados'), ('PAN', 'Panaderia'), ('VER', 'Verduras y hortalizas'), ('CNG', 'Congelados'), ('FLA', 'Frescos y Lacteos')], default='OTR', max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('user_uuid', models.CharField(max_length=36)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comun.Estados')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stock_inicial', models.IntegerField()),
                ('stock_descontado', models.IntegerField()),
                ('stock_final', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('fecha_elaboracion', models.DateField(blank=True)),
                ('fecha_expiracion', models.DateField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('observaciones', models.CharField(default='', max_length=200, null=True)),
                ('user_uuid', models.CharField(max_length=36)),
                ('producto_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.ProductoStock')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comun.Estados')),
            ],
        ),
    ]
