# Generated by Django 2.0.5 on 2018-11-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productostock',
            name='precio',
        ),
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('FRU', 'Frutas'), ('OTR', 'Otros'), ('FLA', 'Frescos y Lacteos'), ('PES', 'Pescados y Mariscos'), ('CNG', 'Congelados'), ('PPD', 'Productos Preparados'), ('VER', 'Verduras y hortalizas'), ('DES', 'Despensa'), ('PAN', 'Panaderia'), ('CAR', 'Carnes rojas y blancas'), ('BEB', 'Bebidas y Licores'), ('PAS', 'Pastaleria')], default='OTR', max_length=3),
        ),
        migrations.AlterField(
            model_name='productostock',
            name='porcion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productostock',
            name='unidad_medida',
            field=models.CharField(default='unidades', max_length=22),
        ),
    ]
