# Generated by Django 2.0.5 on 2018-12-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('PES', 'Pescados y Mariscos'), ('BEB', 'Bebidas y Licores'), ('OTR', 'Otros'), ('PAS', 'Pastaleria'), ('PAN', 'Panaderia'), ('PPD', 'Productos Preparados'), ('VER', 'Verduras y hortalizas'), ('DES', 'Despensa'), ('FRU', 'Frutas'), ('CNG', 'Congelados'), ('FLA', 'Frescos y Lacteos'), ('CAR', 'Carnes rojas y blancas')], default='OTR', max_length=3),
        ),
    ]
