# Generated by Django 2.1.3 on 2018-12-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('PES', 'Pescados y Mariscos'), ('BEB', 'Bebidas y Licores'), ('PAS', 'Pastaleria'), ('CAR', 'Carnes rojas y blancas'), ('PAN', 'Panaderia'), ('CNG', 'Congelados'), ('OTR', 'Otros'), ('FRU', 'Frutas'), ('FLA', 'Frescos y Lacteos'), ('DES', 'Despensa'), ('PPD', 'Productos Preparados'), ('VER', 'Verduras y hortalizas')], default='OTR', max_length=3),
        ),
    ]
