# Generated by Django 2.0.5 on 2018-12-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriastock',
            name='nombreCategoria',
            field=models.CharField(choices=[('BEB', 'BEBIDAS_LICORES'), ('FRU', 'FRUTA'), ('EFE', 'CONGELADOS'), ('VER', 'CARNE'), ('FRE', 'FRESCOS_LACTEOS'), ('DES', 'DESPENSAS')], default='CAR', max_length=3),
        ),
    ]
