# Generated by Django 2.0.5 on 2018-12-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20181204_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('OTR', 'Otros'), ('VER', 'Verduras y hortalizas'), ('CAR', 'Carnes rojas y blancas'), ('PAN', 'Panaderia'), ('FRU', 'Frutas'), ('CNG', 'Congelados'), ('PES', 'Pescados y Mariscos'), ('FLA', 'Frescos y Lacteos'), ('DES', 'Despensa'), ('PAS', 'Pastaleria'), ('PPD', 'Productos Preparados'), ('BEB', 'Bebidas y Licores')], default='OTR', max_length=3),
        ),
    ]
