# Generated by Django 2.0.5 on 2018-11-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20181125_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('PPD', 'Productos Preparados'), ('CAR', 'Carnes rojas y blancas'), ('CNG', 'Congelados'), ('PAN', 'Panaderia'), ('BEB', 'Bebidas y Licores'), ('FRU', 'Frutas'), ('PAS', 'Pastaleria'), ('OTR', 'Otros'), ('FLA', 'Frescos y Lacteos'), ('DES', 'Despensa'), ('VER', 'Verduras y hortalizas'), ('PES', 'Pescados y Mariscos')], default='OTR', max_length=3),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_descontado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_inicial',
            field=models.IntegerField(default=0),
        ),
    ]
