# Generated by Django 2.1.1 on 2018-11-20 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20181119_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productostock',
            name='stock_uuid',
        ),
        migrations.AddField(
            model_name='stock',
            name='observaciones',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='producto_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.ProductoStock'),
        ),
    ]
