# Generated by Django 2.0.5 on 2018-12-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20181203_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('FRU', 'Frutas'), ('PES', 'Pescados y Mariscos'), ('PAS', 'Pastaleria'), ('OTR', 'Otros'), ('CAR', 'Carnes rojas y blancas'), ('PPD', 'Productos Preparados'), ('CNG', 'Congelados'), ('BEB', 'Bebidas y Licores'), ('DES', 'Despensa'), ('PAN', 'Panaderia'), ('VER', 'Verduras y hortalizas'), ('FLA', 'Frescos y Lacteos')], default='OTR', max_length=3),
        ),
    ]
