# Generated by Django 2.0.5 on 2018-12-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20181202_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('VER', 'Verduras y hortalizas'), ('CNG', 'Congelados'), ('DES', 'Despensa'), ('PPD', 'Productos Preparados'), ('PES', 'Pescados y Mariscos'), ('BEB', 'Bebidas y Licores'), ('CAR', 'Carnes rojas y blancas'), ('OTR', 'Otros'), ('FLA', 'Frescos y Lacteos'), ('PAN', 'Panaderia'), ('PAS', 'Pastaleria'), ('FRU', 'Frutas')], default='OTR', max_length=3),
        ),
    ]
