# Generated by Django 2.0.5 on 2018-11-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20181125_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('PES', 'Pescados y Mariscos'), ('OTR', 'Otros'), ('CNG', 'Congelados'), ('DES', 'Despensa'), ('FLA', 'Frescos y Lacteos'), ('PAS', 'Pastaleria'), ('BEB', 'Bebidas y Licores'), ('PPD', 'Productos Preparados'), ('CAR', 'Carnes rojas y blancas'), ('FRU', 'Frutas'), ('PAN', 'Panaderia'), ('VER', 'Verduras y hortalizas')], default='OTR', max_length=3),
        ),
    ]
