# Generated by Django 2.0.5 on 2018-12-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20181202_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('PPD', 'Productos Preparados'), ('PAS', 'Pastaleria'), ('VER', 'Verduras y hortalizas'), ('FLA', 'Frescos y Lacteos'), ('DES', 'Despensa'), ('BEB', 'Bebidas y Licores'), ('CAR', 'Carnes rojas y blancas'), ('OTR', 'Otros'), ('PES', 'Pescados y Mariscos'), ('CNG', 'Congelados'), ('PAN', 'Panaderia'), ('FRU', 'Frutas')], default='OTR', max_length=3),
        ),
    ]
