# Generated by Django 2.1.1 on 2018-11-20 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20181119_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriastock',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comun.Estados'),
        ),
    ]
