# Generated by Django 2.1.3 on 2018-12-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20181204_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('BEB', 'Bebidas y Licores'), ('PPD', 'Productos Preparados'), ('PES', 'Pescados y Mariscos'), ('FLA', 'Frescos y Lacteos'), ('OTR', 'Otros'), ('DES', 'Despensa'), ('PAS', 'Pastaleria'), ('CAR', 'Carnes rojas y blancas'), ('VER', 'Verduras y hortalizas'), ('CNG', 'Congelados'), ('FRU', 'Frutas'), ('PAN', 'Panaderia')], default='OTR', max_length=3),
        ),
    ]
