# Generated by Django 2.1.1 on 2018-11-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20181119_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='fechaElaboracion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productostock',
            name='fechaExpiracion',
            field=models.DateField(),
        ),
    ]
