# Generated by Django 2.0.5 on 2018-11-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20181125_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('FLA', 'Frescos y Lacteos'), ('CNG', 'Congelados'), ('PAN', 'Panaderia'), ('PAS', 'Pastaleria'), ('PES', 'Pescados y Mariscos'), ('BEB', 'Bebidas y Licores'), ('FRU', 'Frutas'), ('OTR', 'Otros'), ('PPD', 'Productos Preparados'), ('CAR', 'Carnes rojas y blancas'), ('DES', 'Despensa'), ('VER', 'Verduras y hortalizas')], default='OTR', max_length=3),
        ),
    ]
