# Generated by Django 2.1.3 on 2018-12-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20181204_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('PES', 'Pescados y Mariscos'), ('DES', 'Despensa'), ('FRU', 'Frutas'), ('CAR', 'Carnes rojas y blancas'), ('OTR', 'Otros'), ('BEB', 'Bebidas y Licores'), ('VER', 'Verduras y hortalizas'), ('PPD', 'Productos Preparados'), ('PAN', 'Panaderia'), ('FLA', 'Frescos y Lacteos'), ('CNG', 'Congelados'), ('PAS', 'Pastaleria')], default='OTR', max_length=3),
        ),
    ]
