# Generated by Django 2.1.3 on 2018-12-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20181204_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('PAS', 'Pastaleria'), ('VER', 'Verduras y hortalizas'), ('FLA', 'Frescos y Lacteos'), ('PAN', 'Panaderia'), ('PPD', 'Productos Preparados'), ('BEB', 'Bebidas y Licores'), ('CAR', 'Carnes rojas y blancas'), ('CNG', 'Congelados'), ('PES', 'Pescados y Mariscos'), ('DES', 'Despensa'), ('FRU', 'Frutas'), ('OTR', 'Otros')], default='OTR', max_length=3),
        ),
    ]
