# Generated by Django 2.0.5 on 2018-11-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20181125_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('FRU', 'Frutas'), ('FLA', 'Frescos y Lacteos'), ('PAS', 'Pastaleria'), ('PPD', 'Productos Preparados'), ('PES', 'Pescados y Mariscos'), ('CAR', 'Carnes rojas y blancas'), ('DES', 'Despensa'), ('VER', 'Verduras y hortalizas'), ('CNG', 'Congelados'), ('BEB', 'Bebidas y Licores'), ('OTR', 'Otros'), ('PAN', 'Panaderia')], default='OTR', max_length=3),
        ),
    ]
