# Generated by Django 2.0.5 on 2018-11-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20181125_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='productostock',
            name='stock_disponible',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('CNG', 'Congelados'), ('PAN', 'Panaderia'), ('PPD', 'Productos Preparados'), ('DES', 'Despensa'), ('OTR', 'Otros'), ('PES', 'Pescados y Mariscos'), ('FRU', 'Frutas'), ('CAR', 'Carnes rojas y blancas'), ('VER', 'Verduras y hortalizas'), ('FLA', 'Frescos y Lacteos'), ('PAS', 'Pastaleria'), ('BEB', 'Bebidas y Licores')], default='OTR', max_length=3),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fecha_elaboracion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fecha_expiracion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
