# Generated by Django 2.1.3 on 2018-12-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20181204_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('PES', 'Pescados y Mariscos'), ('PAS', 'Pastaleria'), ('PAN', 'Panaderia'), ('CNG', 'Congelados'), ('PPD', 'Productos Preparados'), ('BEB', 'Bebidas y Licores'), ('CAR', 'Carnes rojas y blancas'), ('OTR', 'Otros'), ('VER', 'Verduras y hortalizas'), ('DES', 'Despensa'), ('FLA', 'Frescos y Lacteos'), ('FRU', 'Frutas')], default='OTR', max_length=3),
        ),
    ]
