# Generated by Django 2.0.5 on 2018-11-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20181125_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('PPD', 'Productos Preparados'), ('VER', 'Verduras y hortalizas'), ('CAR', 'Carnes rojas y blancas'), ('BEB', 'Bebidas y Licores'), ('PES', 'Pescados y Mariscos'), ('FRU', 'Frutas'), ('FLA', 'Frescos y Lacteos'), ('OTR', 'Otros'), ('PAS', 'Pastaleria'), ('CNG', 'Congelados'), ('PAN', 'Panaderia'), ('DES', 'Despensa')], default='OTR', max_length=3),
        ),
    ]
