# Generated by Django 2.1.3 on 2018-12-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20181204_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='categoria',
            field=models.CharField(choices=[('PPD', 'Productos Preparados'), ('PES', 'Pescados y Mariscos'), ('CAR', 'Carnes rojas y blancas'), ('PAS', 'Pastaleria'), ('CNG', 'Congelados'), ('PAN', 'Panaderia'), ('BEB', 'Bebidas y Licores'), ('VER', 'Verduras y hortalizas'), ('OTR', 'Otros'), ('DES', 'Despensa'), ('FRU', 'Frutas'), ('FLA', 'Frescos y Lacteos')], default='OTR', max_length=3),
        ),
    ]
