# Generated by Django 2.0.5 on 2018-12-02 21:39

from django.db import migrations, models
import django.db.models.deletion
import mesas.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('identificador', models.CharField(max_length=20)),
                ('empleado', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('FRE', 'Libre'), ('OCP', 'Ocupada'), ('RSV', 'Reservada')], default='FRE', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('numero', models.IntegerField(default=mesas.models.Reserva.ids, editable=False, unique=True, verbose_name='Code')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_numero1', models.CharField(max_length=30)),
                ('cliente_numero2', models.CharField(blank=True, max_length=30, null=True)),
                ('cliente_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('num_personas', models.IntegerField(default=1)),
                ('comentarios', models.CharField(blank=True, max_length=300, null=True)),
                ('empleado', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('mesa_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesas.Mesas')),
            ],
        ),
    ]
