# Generated by Django 2.0.5 on 2018-12-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesas',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='mesas',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='mesas',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='mesas',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='mesas',
            name='termino',
        ),
        migrations.AlterField(
            model_name='mesas',
            name='estado',
            field=models.CharField(choices=[('FRE', 'Libre'), ('OCP', 'Ocupada'), ('RSV', 'Reservada')], default='RSV', max_length=3),
        ),
    ]
