# Generated by Django 2.0.5 on 2018-12-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0003_auto_20181202_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='identificador',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
